// Generated by the Supabase MCP `generate_typescript_types` tool — do not edit
// by hand. Regenerate after every migration (see CLAUDE.md).
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      attempts: {
        Row: {
          answers: Json
          cell_max: number
          cell_score: number
          client_submission_id: string
          confidence: number | null
          created_at: string
          duration_ms: number | null
          feedback: Json
          id: string
          item_id: string
          item_version: number
          session_id: string | null
          tx_correct: number
          tx_total: number
          user_id: string
        }
        Insert: {
          answers: Json
          cell_max: number
          cell_score: number
          client_submission_id: string
          confidence?: number | null
          created_at?: string
          duration_ms?: number | null
          feedback: Json
          id?: string
          item_id: string
          item_version: number
          session_id?: string | null
          tx_correct: number
          tx_total: number
          user_id?: string
        }
        Update: {
          answers?: Json
          cell_max?: number
          cell_score?: number
          client_submission_id?: string
          confidence?: number | null
          created_at?: string
          duration_ms?: number | null
          feedback?: Json
          id?: string
          item_id?: string
          item_version?: number
          session_id?: string | null
          tx_correct?: number
          tx_total?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "attempts_item_id_fkey"
            columns: ["item_id"]
            isOneToOne: false
            referencedRelation: "learning_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "attempts_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "practice_sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      error_log: {
        Row: {
          attempt_id: string
          cell: string
          created_at: string
          expected_label: string
          id: string
          item_id: string
          paper: string | null
          resolved: boolean
          row_id: string
          row_label: string
          submitted_label: string
          topic: string | null
          user_id: string
        }
        Insert: {
          attempt_id: string
          cell: string
          created_at?: string
          expected_label?: string
          id?: string
          item_id: string
          paper?: string | null
          resolved?: boolean
          row_id: string
          row_label?: string
          submitted_label?: string
          topic?: string | null
          user_id?: string
        }
        Update: {
          attempt_id?: string
          cell?: string
          created_at?: string
          expected_label?: string
          id?: string
          item_id?: string
          paper?: string | null
          resolved?: boolean
          row_id?: string
          row_label?: string
          submitted_label?: string
          topic?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "error_log_attempt_id_fkey"
            columns: ["attempt_id"]
            isOneToOne: false
            referencedRelation: "attempts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "error_log_item_id_fkey"
            columns: ["item_id"]
            isOneToOne: false
            referencedRelation: "learning_items"
            referencedColumns: ["id"]
          },
        ]
      }
      learning_item_answers: {
        Row: {
          answer_key: Json
          created_at: string
          item_id: string
          overall_explanation_md: string | null
          version: number
        }
        Insert: {
          answer_key: Json
          created_at?: string
          item_id: string
          overall_explanation_md?: string | null
          version: number
        }
        Update: {
          answer_key?: Json
          created_at?: string
          item_id?: string
          overall_explanation_md?: string | null
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "learning_item_answers_item_id_fkey"
            columns: ["item_id"]
            isOneToOne: false
            referencedRelation: "learning_items"
            referencedColumns: ["id"]
          },
        ]
      }
      learning_items: {
        Row: {
          config: Json
          created_at: string
          created_by: string | null
          difficulty: string | null
          id: string
          kind: string
          paper: string | null
          prompt_md: string
          source_slug: string | null
          status: string
          syllabus_area: string | null
          tags: string[]
          title: string
          topic: string | null
          updated_at: string
          version: number
        }
        Insert: {
          config?: Json
          created_at?: string
          created_by?: string | null
          difficulty?: string | null
          id?: string
          kind: string
          paper?: string | null
          prompt_md?: string
          source_slug?: string | null
          status?: string
          syllabus_area?: string | null
          tags?: string[]
          title: string
          topic?: string | null
          updated_at?: string
          version?: number
        }
        Update: {
          config?: Json
          created_at?: string
          created_by?: string | null
          difficulty?: string | null
          id?: string
          kind?: string
          paper?: string | null
          prompt_md?: string
          source_slug?: string | null
          status?: string
          syllabus_area?: string | null
          tags?: string[]
          title?: string
          topic?: string | null
          updated_at?: string
          version?: number
        }
        Relationships: []
      }
      mcp_tokens: {
        Row: {
          created_at: string
          label: string | null
          token: string
        }
        Insert: {
          created_at?: string
          label?: string | null
          token: string
        }
        Update: {
          created_at?: string
          label?: string | null
          token?: string
        }
        Relationships: []
      }
      notes: {
        Row: {
          content: string
          created_at: string
          folder: string
          id: string
          slug: string
          title: string
          updated_at: string
        }
        Insert: {
          content?: string
          created_at?: string
          folder?: string
          id?: string
          slug: string
          title: string
          updated_at?: string
        }
        Update: {
          content?: string
          created_at?: string
          folder?: string
          id?: string
          slug?: string
          title?: string
          updated_at?: string
        }
        Relationships: []
      }
      practice_sessions: {
        Row: {
          completed_at: string | null
          id: string
          item_id: string | null
          quiz_id: string | null
          started_at: string
          status: string
          user_id: string
        }
        Insert: {
          completed_at?: string | null
          id?: string
          item_id?: string | null
          quiz_id?: string | null
          started_at?: string
          status?: string
          user_id?: string
        }
        Update: {
          completed_at?: string | null
          id?: string
          item_id?: string | null
          quiz_id?: string | null
          started_at?: string
          status?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "practice_sessions_item_id_fkey"
            columns: ["item_id"]
            isOneToOne: false
            referencedRelation: "learning_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "practice_sessions_quiz_id_fkey"
            columns: ["quiz_id"]
            isOneToOne: false
            referencedRelation: "quizzes"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          created_at: string
          display_name: string | null
          role: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          display_name?: string | null
          role?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          display_name?: string | null
          role?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      quiz_items: {
        Row: {
          item_id: string
          position: number
          quiz_id: string
        }
        Insert: {
          item_id: string
          position: number
          quiz_id: string
        }
        Update: {
          item_id?: string
          position?: number
          quiz_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "quiz_items_item_id_fkey"
            columns: ["item_id"]
            isOneToOne: false
            referencedRelation: "learning_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quiz_items_quiz_id_fkey"
            columns: ["quiz_id"]
            isOneToOne: false
            referencedRelation: "quizzes"
            referencedColumns: ["id"]
          },
        ]
      }
      quizzes: {
        Row: {
          created_at: string
          created_by: string | null
          description_md: string
          difficulty: string | null
          est_minutes: number | null
          id: string
          paper: string | null
          status: string
          syllabus_area: string | null
          tags: string[]
          timed: boolean
          title: string
          topic: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          description_md?: string
          difficulty?: string | null
          est_minutes?: number | null
          id?: string
          paper?: string | null
          status?: string
          syllabus_area?: string | null
          tags?: string[]
          timed?: boolean
          title: string
          topic?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          description_md?: string
          difficulty?: string | null
          est_minutes?: number | null
          id?: string
          paper?: string | null
          status?: string
          syllabus_area?: string | null
          tags?: string[]
          timed?: boolean
          title?: string
          topic?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      review_states: {
        Row: {
          due_at: string | null
          item_id: string
          last_score: number | null
          streak: number
          updated_at: string
          user_id: string
        }
        Insert: {
          due_at?: string | null
          item_id: string
          last_score?: number | null
          streak?: number
          updated_at?: string
          user_id?: string
        }
        Update: {
          due_at?: string | null
          item_id?: string
          last_score?: number | null
          streak?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "review_states_item_id_fkey"
            columns: ["item_id"]
            isOneToOne: false
            referencedRelation: "learning_items"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      add_note: {
        Args: { p_content: string; p_folder?: string; p_title: string }
        Returns: {
          content: string
          created_at: string
          folder: string
          id: string
          slug: string
          title: string
          updated_at: string
        }
        SetofOptions: {
          from: "*"
          to: "notes"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      current_app_role: { Args: never; Returns: string }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
